--PATH tableName < DEMT.sql
--PATH tableName < ENP.sql

CREATE TABLE SALGRADE (GRADE INT, LOSAL INT, HISAL INT);

insert into SALGRADE VALUE(1, 700, 1200);
insert into SALGRADE VALUE(2, 1201, 1400);
insert into SALGRADE VALUE(3, 1401, 2000);
insert into SALGRADE VALUE(4, 2001, 3000);
insert into SALGRADE VALUE(5, 3001, 9999);


CREATE TABLE SUBEMP (
  EMPNO INT,
  ENAME VARCHAR,
  JOB CHAR,
  MGR INT,
  HIREDATE DATE,
  SAL INT,
  DEPTNO INT
);

INSERT INTO `SUBEMP` VALUES (10001,'ALEX','PRESIDENT',NULL,'2010-03-01',2800,40);
INSERT INTO `SUBEMP` VALUES (10002,'BOB','CLERK',10001,'2010-03-01',600,40);
INSERT INTO `SUBEMP` VALUES (7369,'SMITH','CLERK',7902,'2001-12-17',800,20);

-- Q_1
ALTER TABLE EMP MODIFY COLUMN EMPNO INT NOT NULL;

-- Query OK, 14 rows affected (0.07 sec)
-- Records: 14  Duplicates: 0  Warnings: 0

ALTER TABLE SUBEMP MODIFY COLUMN EMPNO INT NOT NULL;

-- Query OK, 3 rows affected (0.11 sec)
-- Records: 3  Duplicates: 0  Warnings: 0

-- Q_2
SELECT a.JOB, b.LOC 
from EMP AS a 
LEFT JOIN DEMT AS b 
ON a.DEMTNO = b.DEPTNO
WHERE a.JOB IN ('PRESIDENT', 'CLERK')
UNION ALL
SELECT a.JOB, b.LOC 
from SUBEMP AS a 
LEFT JOIN DEMT AS b 
ON a.DEPTNO = b.DEPTNO
WHERE a.JOB IN ('PRESIDENT', 'CLERK');

-- Q_3 TODO
SELECT a.GRADE, count(b.SAL) 
FROM SALGRADE AS a 
LEFT JOIN EMP AS b ON a.LOSAL <= b.SAL AND b.SAL <= a.HISAL 
GROUP BY a.GRADE
UNION ALL
SELECT a.GRADE, count(b.SAL) 
FROM SALGRADE AS a 
LEFT JOIN SUBEMP AS b ON a.LOSAL <= b.SAL AND b.SAL <= a.HISAL 
GROUP BY a.GRADE;

-- Q_4

